# Generated by Django 5.1.7 on 2025-07-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_settings_subreddit_is_active_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='reddit_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=511)),
                ('content', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('subreddit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.subreddit')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='post_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.post'),
        ),
        migrations.AddField(
            model_name='image',
            name='post_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.post'),
        ),
    ]
