# Generated by Django 5.1.7 on 2025-07-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_reddit_id_subreddit_display_name_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
