# Generated by Django 5.1.7 on 2025-07-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_gallery_title_remove_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
