# Generated by Django 5.1.7 on 2025-07-17 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_ignoredposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='post_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.post'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.post'),
        ),
    ]
