# Generated by Django 5.1.7 on 2025-07-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_gallery_post_ref_alter_image_post_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('excluded_subreddits', models.TextField(blank=True, help_text='Comma-separated list of subreddits to ignore to view From the gallery.', null=True)),
                ('downloads_folder', models.CharField(blank=True, help_text='Folder where images will be downloaded.', max_length=255, null=True)),
            ],
        ),
    ]
