# Generated by Django 5.1.7 on 2025-07-22 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_mainsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.subreddit'),
        ),
        migrations.CreateModel(
            name='SavedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(blank=True, max_length=255)),
                ('downloaded_at', models.FilePathField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.image')),
                ('subreddit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.subreddit')),
            ],
        ),
    ]
