# Generated by Django 5.1.7 on 2025-10-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_subreddit_excluded_alter_post_subreddit_savedimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Undefined', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subreddits', models.ManyToManyField(blank=True, related_name='categories', to='gallery.subreddit', verbose_name='subreddits')),
            ],
        ),
    ]
